# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_fristmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 754)
        MainWindow.setStyleSheet("background-color: rgba(0, 0, 0, 0);");
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 611, 691))
        self.label.setStyleSheet("border-image: url(:/img/icon/background1.jpg);\n"
"\n"
"border-top-left-radius:60px;\n"
"border-bottom-left-radius:60px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 40, 611, 691))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"border-top-right-radius:60px;\n"
"border-bottom-right-radius:60px")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 110, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_3.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 170, 611, 61))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.maxButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.maxButton_4.setGeometry(QtCore.QRect(1100, 70, 50, 28))
        self.maxButton_4.setMinimumSize(QtCore.QSize(50, 28))
        self.maxButton_4.setMaximumSize(QtCore.QSize(50, 28))
        self.maxButton_4.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.maxButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/正方形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/img/icon/还原.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/img/icon/还原.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.maxButton_4.setIcon(icon)
        self.maxButton_4.setCheckable(True)
        self.maxButton_4.setObjectName("maxButton_4")
        self.closeButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton_4.setGeometry(QtCore.QRect(1150, 70, 50, 28))
        self.closeButton_4.setMinimumSize(QtCore.QSize(50, 28))
        self.closeButton_4.setMaximumSize(QtCore.QSize(50, 28))
        self.closeButton_4.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.closeButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton_4.setIcon(icon1)
        self.closeButton_4.setObjectName("closeButton_4")
        self.minButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.minButton_4.setGeometry(QtCore.QRect(1050, 70, 50, 28))
        self.minButton_4.setMinimumSize(QtCore.QSize(50, 28))
        self.minButton_4.setMaximumSize(QtCore.QSize(50, 28))
        self.minButton_4.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.minButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton_4.setIcon(icon2)
        self.minButton_4.setObjectName("minButton_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(660, 210, 581, 181))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(14);
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(670, 660, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(12);
        font.setFamily("Fixedsys")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 380, 381, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
                                        "{        \n"
                                        "\n"
                                        "         border-radius:9px;\n"
                                        "        background:rgb(40, 40, 40);\n"
                                        "color: rgb(218, 218, 218);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed\n"
                                        "{        \n"
                                        "        padding-left:4px;\n"
                                        "        padding-top:4px;\n"
                                        "         border-radius:9px;\n"
                                        "        background:rgb(40, 40, 40);\n"
                                        "color: rgb(218, 218, 218);\n"
                                        "}\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 500, 381, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
                                        "{        \n"
                                        "\n"
                                        "         border-radius:9px;\n"
                                        "        background:rgb(40, 40, 40);\n"
                                        "color: rgb(218, 218, 218);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed\n"
                                        "{        \n"
                                        "        padding-left:4px;\n"
                                        "        padding-top:4px;\n"
                                        "         border-radius:9px;\n"
                                        "        background:rgb(40, 40, 40);\n"
                                        "color: rgb(218, 218, 218);\n"
                                        "}\n"
                                        "")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Recognition System"))
        self.label_3.setText(_translate("MainWindow", "Welcome to Underwater"))
        self.label_4.setText(_translate("MainWindow", "  Visual Recognition System !"))
        self.label_11.setText(_translate("MainWindow", "The system now offers object detection and object tracking functions, please select the function you want to use."))
        self.label_12.setText(_translate("MainWindow", ""))
        self.pushButton_3.setText(_translate("MainWindow", "Object Tracking"))
        self.pushButton.setText(_translate("MainWindow", "Object Detection"))
import appr.apprcc
